<a href="https://colab.research.google.com/github/lmillana/MasterProjects/blob/main/SQL/%20SQL%20Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MODELOS E-R**

[Modelos relacionales en MIRO](https://miro.com/welcomeonboard/bEpXZ3pQQ1cwWjY1MFphY3cxNjNxQ2p4cWJGUDMwSkljS2pGNlFkaFRKUHp1SGVEaTVRZm01NDNrWVYyWld6TXwzNDU4NzY0NTgwMTg4NDE3NTIzfDI=?share_link_id=490188444006)

## **Semana 1 - La cena de Iván**

**Descripción:**

Iván es un entusiasta de la cocina que disfruta experimentar con nuevas recetas.

Recientemente ha organizado una cena para sus amigos y quiere impresionarlos con una selección de deliciosos platos.

Iván ha preparado una lista de ingredientes necesarios para sus recetas y ha guardado esta información en una base de datos.

Tu tarea es ayudar a Iván a gestionar sus ingredientes y recetas creando una base de datos y realizando algunas consultas para facilitar la preparación de su cena.

**Datos:**

La base de datos contiene dos tablas:
- una tabla llamada `recetas`
- otra tabla llamada `ingredientes`.

Aquí está la **estructura de ambas tablas**:

**Tabla recetas**:

- receta_id (int, clave primaria): Identificador único de la receta.
- nombre_receta (string): Nombre de la receta.
- categoria (string): Categoría a la que pertenece la receta (por ejemplo, entrante, plato principal, postre).
- tiempo_preparacion (int): Tiempo estimado de preparación en minutos.
- dificultad (string): Nivel de dificultad de la receta (por ejemplo, fácil, intermedio, difícil).

**Tabla ingredientes:**

- ingrediente_id (int, clave primaria): Identificador único del ingrediente.
- nombre_ingrediente (string): Nombre del ingrediente.
- cantidad_disponible (int): Cantidad disponible del ingrediente en la despensa de Iván.
- unidad_medida (string): Unidad de medida del ingrediente (por ejemplo, gramos, mililitros).

**Tareas:**

1. Crea la estructura de la base de datos con las tablas recetas e ingredientes. Hazlo en un diagrama E-R.

2. Inserta al menos 5 registros en cada tabla para simular recetas y sus ingredientes.

3. Realiza consultas SQL para realizar las siguientes acciones:
- Mostrar todas las recetas disponibles.
- Mostrar todos los ingredientes necesarios para una receta específica.
- Mostrar las recetas que se pueden preparar con los ingredientes disponibles en la despensa de Iván.
- Mostrar las recetas que requieren una cantidad mínima de un ingrediente específico que Iván aún no tiene en su despensa.


**Entrega:**

Proporciona el script SQL que incluya la creación de las tablas, la inserción de datos y las consultas realizadas para cumplir con las tareas mencionadas.

In [ ]:
import numpy as np
import pandas as pd #Pandas: para manipulación y análisis de datos
import sqlite3 #para trabajar con BBDD SQLite

#Creamos nuestra base de datos: recetas
conn = sqlite3.connect('cocina.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

In [ ]:

## TAREA 1 - RECETAS
# Crear la estructura de la base de datos con las tablas recetas e ingredientes.

# Creamos la tabla: RECETAS
conn.execute('''
CREATE TABLE recetas (
    receta_id INTEGER PRIMARY KEY AUTOINCREMENT ,
    nombre_receta varchar(40) NOT NULL,
    categoria varchar(40) NOT NULL,
    tiempo_preparacion INT,
    dificultad varchar(10)
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - RECETAS
#Inserta al menos 5 registros en cada tabla para simular recetas y sus ingredientes.

conn = sqlite3.connect('cocina.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO recetas (nombre_receta, categoria, tiempo_preparacion, dificultad)
VALUES ('tortilla de patata','entrante', 35, 'facil'),
       ('tortitas','desayuno', 20, 'facil'),
       ('macarrones con tomate','principal', 35, 'media'),
       ('brownie','postre', 25, 'facil'),
       ('lentejas','principal', 60, 'media');
''')

# Guardar los cambios
conn.commit()

In [ ]:
# Para VACIAR TABLA en caso de ERROR:
conn.execute('''
DROP TABLE recetas;
''')
conn.commit()
conn.close()

In [ ]:
## TAREA 1 - INGREDIENTES
# Crear la estructura de la base de datos con las tablas recetas e ingredientes.
# Esta tabla muestra los alimentos y cantidades disponibles en la cocina

# Creamos la tabla: INGREDIENTES

conn = sqlite3.connect('cocina.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
CREATE TABLE ingredientes (
    ingrediente_id INTEGER PRIMARY KEY AUTOINCREMENT ,
    nombre_ingrediente varchar(40) NOT NULL,
    cantidad_disponible INT,
    unidad_medida varchar(10)
);''')

# Guardar los cambios
conn.commit()

# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - INGREDIENTES
#Inserta al menos 5 registros en cada tabla para simular recetas y sus ingredientes.

conn = sqlite3.connect('cocina.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

#Añadimos registro a la tabla INGREDIENTES:
conn.execute('''
INSERT INTO ingredientes (nombre_ingrediente, cantidad_disponible, unidad_medida)
VALUES ('huevo', 10, 'unidades'),
       ('patata', 2000, 'gramos'),
       ('harina', 1000, 'gramos'),
       ('mantequilla', 100, 'gramos'),
       ('leche', 1000, 'centilitros'),
       ('macarrones', 100, 'gramos'),
       ('tomate frito', 500, 'gramos'),
       ('chocolate', '100', 'gramos'),
       ('lenteja', 1000, 'gramos'),
       ('chorizo', 3, 'unidades'),
       ('pimiento', 5, 'unidades');
''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
 ## TAREA 1 - INSTRUCCIONES
# Crear la estructura de la base de datos con las tablas recetas e ingredientes.
# Tabla de unión entre RECETAS E INGREDIENTES:

# Creamos la tabla: INSTRUCCIONES

conn = sqlite3.connect('cocina.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
CREATE TABLE instrucciones (
    nombre_receta varchar(40) NOT NULL,
    nombre_ingrediente varchar(40) NOT NULL,
    cantidad_necesaria INT,
    FOREIGN KEY (nombre_receta) REFERENCES recetas(nombre_receta),
    FOREIGN KEY (nombre_ingrediente) REFERENCES nevera(nombre_ingrediente)
);''')

# Guardar los cambios
conn.commit()

# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - INSTRUCCIONES
#Inserta al menos 5 registros en cada tabla para simular recetas y sus ingredientes.

conn = sqlite3.connect('cocina.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

#Añadimos registro a la tabla INSTRUCCIONES:
conn.execute('''
INSERT INTO instrucciones (nombre_receta, nombre_ingrediente, cantidad_necesaria)
VALUES ('tortilla de patata', 'patatas', 200),
       ('tortilla de patata', 'huevos', 2),
       ('tortitas', 'huevos', 1),
       ('tortitas', 'harina', 150),
       ('tortitas', 'mantequilla', 30),
       ('tortitas', 'leche', 200),
       ('macarrones con tomate', 'macarrones', 150),
       ('macarrones con tomate', 'tomate frito', 50),
       ('macarrones con tomate', 'pimiento', 1),
       ('brownie', 'huevos', 1),
       ('brownie', 'harina', 150),
       ('brownie', 'mantequilla', 30),
       ('brownie', 'leche', 200),
       ('brownie', 'chocolate', 150);
''')

# Guardar los cambios
conn.commit()

In [ ]:
## TAREA 3
# 1- Mostrar todas las recetas disponibles.

qry ='''SELECT *
FROM instrucciones;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(10) # Muestra las primeras 10 filas

           nombre_receta nombre_ingrediente  cantidad_necesaria
0     tortilla de patata            patatas                 200
1     tortilla de patata             huevos                   2
2               tortitas             huevos                   1
3               tortitas             harina                 150
4               tortitas        mantequilla                  30
5               tortitas              leche                 200
6  macarrones con tomate         macarrones                 150
7  macarrones con tomate       tomate frito                  50
8  macarrones con tomate           pimiento                   1
9                brownie             huevos                   1

In [ ]:
## TAREA 3
# 2- Mostrar todos los ingredientes necesarios para una receta específica.

qry ='''SELECT nombre_ingrediente
FROM instrucciones
WHERE nombre_receta = 'brownie'
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(10) # Muestra las primeras 10 filas

  nombre_ingrediente
0             huevos
1             harina
2        mantequilla
3              leche
4          chocolate

In [ ]:
## TAREA 3
# 3- Mostrar las recetas que se pueden preparar con los ingredientes disponibles

qry ='''SELECT nombre_receta
FROM instrucciones
WHERE nombre_ingrediente = 'huevos'
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(10) # Muestra las primeras 10 filas

        nombre_receta
0  tortilla de patata
1            tortitas
2             brownie

In [ ]:
## TAREA 3
# 4- Mostrar las recetas que requieren una cantidad mínima de un ingrediente específico que Iván aún no tiene en su despensa.
# Muestra aquellas recetas donde la cantidad disponible no es suficiente para realizar la receta

qry ='''SELECT nombre_receta
FROM instrucciones
JOIN ingredientes
ON instrucciones.nombre_ingrediente = ingredientes.nombre_ingrediente
WHERE cantidad_necesaria > cantidad_disponible
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

           nombre_receta
0  macarrones con tomate
1                brownie

## **Semana 2 - Telepizza**

**Descripción:**

Telepizza es una cadena de restaurantes de pizzas que opera en España.
Están interesados en mejorar su sistema de gestión de pedidos y entregas, y para eso necesitan una base de datos que les ayude a gestionar esta información.

**Datos:**

La base de datos de Telepizza contiene tres tablas principales:
- orders (pedidos),
- runners (repartidores) y
- pizza_types (tipos de pizza).

Aquí está la estructura de cada tabla:

**Tabla orders:**

- order_id (int, clave primaria): Identificador único del pedido.
- customer_id (int): Identificador único del cliente que realizó el pedido.
- pizza_id (int): Identificador único del tipo de pizza solicitado.
- runner_id (int): Identificador único del repartidor asignado al pedido.
- order_time (timestamp): Fecha y hora en la que se realizó el pedido.
- pickup_time (timestamp): Fecha y hora en la que el pedido fue recogido por el repartidor.
- delivery_time (timestamp): Fecha y hora en la que el pedido fue entregado al cliente.

**Tabla runners:**

- runner_id (int, clave primaria): Identificador único del repartidor.
- name (string): Nombre del repartidor.
- age (int): Edad del repartidor.
- rating (float): Calificación promedio del repartidor.

**Tabla pizza_types:**

- pizza_id (int, clave primaria): Identificador único del tipo de pizza.
- pizza_name (string): Nombre del tipo de pizza.
- toppings (string): Ingredientes o toppings que incluye la pizza.
- price (decimal): Precio de la pizza.

**Tareas:**

1. Diseñar e implementar la estructura de la base de datos con las tablas orders, runners y pizza_types.
2. Insertar datos de ejemplo en cada tabla para simular pedidos, repartidores y tipos de pizza.
3. Realizar consultas SQL para responder las siguientes preguntas:
- ¿Cuántas pizzas de cada tipo se han vendido en el último mes?
- ¿Cuál es el repartidor con mejor calificación promedio?
- ¿Cuál es el tiempo promedio de entrega de pedidos?
- ¿Cuál es el tipo de pizza más popular entre los clientes?

**Entrega:**

Proporciona el script SQL que incluya la creación de las tablas, la inserción de datos y las consultas realizadas para cumplir con las tareas mencionadas.

In [ ]:
conn.close()

In [ ]:
import numpy as np
import pandas as pd #Pandas: para manipulación y análisis de datos
import sqlite3 #para trabajar con BBDD SQLite

#Creamos nuestra base de datos: recetas
conn = sqlite3.connect('telepizza.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

## TAREA 1 - TABLA ORDERS
# Crear la estructura de la base de datos de la tabla ORDERS.

conn.execute('''
CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INT NOT NULL,
    pizza_id INT NOT NULL,
    runner_id INT NOT NULL,
    order_time TIMESTAMP,
    pickup_time TIMESTAMP,
    delivery_time TIMESTAMP
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA ORDERS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('telepizza.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO orders (customer_id, pizza_id, runner_id, order_time, pickup_time, delivery_time)
VALUES (1, 2, 2, '2023-12-12 22:00:00', '2023-12-12 22:20:00', '2023-12-12 21:27:30'),
       (2, 1, 1, '2024-01-23 21:00:00', '2024-01-23 21:20:00', '2024-01-23 21:25:30'),
       (2, 3, 1, '2024-01-23 21:00:00', '2024-01-23 21:20:00', '2024-01-23 21:25:30'),
       (3, 2, 2, '2024-02-12 22:00:00', '2024-02-12 22:20:00', '2024-02-12 21:27:30'),
       (4, 1, 3, '2024-02-26 21:45:00', '2024-02-26 22:10:00', '2024-02-26 22:25:30'),
       (5, 1, 2, '2024-02-29 14:00:00', '2024-02-29 14:20:00', '2024-02-29 14:37:30');
''')

# Guardar los cambios
conn.commit()

In [ ]:
# Para VACIAR TABLA en caso de ERROR:
conn.execute('''
DROP TABLE orders;
''')
conn.commit()

In [ ]:
## TAREA 1 - TABLA RUNNERS
# Crear la estructura de la base de datos de la tabla ORDERS.

conn = sqlite3.connect('telepizza.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD


conn.execute('''
CREATE TABLE runners (
    runner_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name varchar(40) NOT NULL,
    age INT NOT NULL,
    rating FLOAT NOT NULL,
    FOREIGN KEY (runner_id) REFERENCES orders(runner_id)
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA RUNNERS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('telepizza.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO runners (name, age, rating)
VALUES ('Petalo', 20, 9.0),
       ('Burburja', 21, 9.2),
       ('Cactus', 22, 9.3);
''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 1 - TABLA PIZZA_TYPES
# Crear la estructura de la base de datos de la tabla PIZZA_TYPES.

conn = sqlite3.connect('telepizza.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD


conn.execute('''
CREATE TABLE pizza_types (
    pizza_id INTEGER PRIMARY KEY AUTOINCREMENT ,
    pizza_name varchar(20) NOT NULL,
    topping varchar(45) NOT NULL,
    price FLOAT NOT NULL,
    FOREIGN KEY (pizza_id) REFERENCES orders(pizza_id)
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA PIZZA_TYPES
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('telepizza.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO pizza_types (pizza_name, topping, price)
VALUES ('Barbacoa', 'bacon, barbacoa, maiz', 13.9),
       ('Carbonara', 'bacon, queso, champiñon', 12.9),
       ('Cuatro quesos', 'cheddar, edam, cabra', 14.9);
''')

# Guardar los cambios
conn.commit()

In [ ]:
# Tabla ORDERS:

qry ='''SELECT *
FROM orders;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(6) # Muestra las primeras 5 filas

,order_id,customer_id,pizza_id,runner_id,order_time,pickup_time,delivery_time
0,1,1,2,2,2023-12-12 22:00:00,2023-12-12 22:20:00,2023-12-12 21:27:30
1,2,2,1,1,2024-01-23 21:00:00,2024-01-23 21:20:00,2024-01-23 21:25:30
2,3,2,3,1,2024-01-23 21:00:00,2024-01-23 21:20:00,2024-01-23 21:25:30
3,4,3,2,2,2024-02-12 22:00:00,2024-02-12 22:20:00,2024-02-12 21:27:30
4,5,4,1,3,2024-02-26 21:45:00,2024-02-26 22:10:00,2024-02-26 22:25:30
5,6,5,1,2,2024-02-29 14:00:00,2024-02-29 14:20:00,2024-02-29 14:37:30

In [ ]:
## TAREA 3:

#1 - ¿Cuántas pizzas de cada tipo se han vendido en el último mes?

qry ='''
SELECT pizza_id, count(*)
FROM orders
WHERE order_time >= '2024-01-01 00:00:00'
group by pizza_id
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

   pizza_id  count(*)
0         1         3
1         2         1
2         3         1

In [ ]:
## TAREA 3:

#2 - ¿Cuál es el repartidor con mejor calificación promedio?

qry ='''
SELECT name
FROM runners
ORDER BY rating DESC
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(1)

     name
0  Cactus

In [ ]:
## TAREA 3

#3 - ¿Cuál es el tiempo promedio de entrega de pedidos?

qry ='''
SELECT AVG((julianday(delivery_time) - julianday(order_time)) * 24 * 60) AS promedio
FROM orders
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

# Devuelve el resultado en MINUTOS; si quisiéramos en segundos:
# SELECT AVG(strftime('%s', delivery_time) - strftime('%s', order_time)) as promedio

    promedio
0  10.666667

In [ ]:
## TAREA 3:

#4- ¿Cuál es el tipo de pizza más popular entre los clientes?

qry ='''
SELECT pizza_types.pizza_name
FROM orders
JOIN pizza_types
ON orders.pizza_id = pizza_types.pizza_id
group by orders.pizza_id
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(1)

  pizza_name
0   Barbacoa

## **Semana 3 - Nod-Foody**

**Descripción:**

Nod-Foody es una startup que ofrece un servicio de entrega de alimentos a través de una plataforma en línea.
Para mejorar su eficiencia y experiencia del usuario, necesitan una base de datos que les permita gestionar los restaurantes registrados, los usuarios y los pedidos realizados en su plataforma.

**Datos:**

La base de datos de Nod-Foody contiene tres tablas principales:
- restaurants (restaurantes),
- users (usuarios)
- orders (pedidos).

Aquí está la estructura de cada tabla:

**Tabla restaurants:**

- restaurant_id (int, clave primaria): Identificador único del restaurante.
- name (string): Nombre del restaurante.
- location (string): Ubicación del restaurante.
- cuisine (string): Tipo de cocina ofrecida por el restaurante (por ejemplo, italiana, mexicana, asiática).

**Tabla users:**

- user_id (int, clave primaria): Identificador único del usuario.
- name (string): Nombre del usuario.
- email (string): Dirección de correo electrónico del usuario.
- address (string): Dirección de entrega del usuario.

**Tabla orders:**

- order_id (int, clave primaria): Identificador único del pedido.
- user_id (int): Identificador único del usuario que realizó el pedido.
- restaurant_id (int): Identificador único del restaurante del cual se realizó el pedido.
- order_time (timestamp): Fecha y hora en la que se realizó el pedido.
- delivery_time (timestamp): Fecha y hora en la que se entregó el pedido al usuario.
- total_amount (decimal): Monto total del pedido.

**Tareas:**

1. Diseñar e implementar la estructura de la base de datos con las tablas restaurants, users y orders.
2. Insertar datos de ejemplo en cada tabla para simular restaurantes registrados, usuarios y pedidos realizados.
3. Realizar consultas SQL para responder las siguientes preguntas:
- ¿Cuántos pedidos se han realizado en cada restaurante durante el último mes?
- ¿Cuál es el usuario que ha realizado más pedidos?
- ¿Cuál es el restaurante más popular entre los usuarios?
- ¿Cuál es el monto total de ventas realizadas en la plataforma durante el último año?

**Entrega:**
Proporciona el script SQL que incluya la creación de las tablas, la inserción de datos y las consultas realizadas para cumplir con las tareas mencionadas.

In [ ]:
## TAREA 1 - TABLA RESTAURANTS
# Crear la estructura de la base de datos de la tabla ORDERS.

import numpy as np
import pandas as pd #Pandas: para manipulación y análisis de datos
import sqlite3 #para trabajar con BBDD SQLite

conn = sqlite3.connect('foody.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
CREATE TABLE restaurants (
    restaurant_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name varchar(40) NOT NULL,
    location varchar(40) NOT NULL,
    cuisine varchar(40) NOT NULL,
    rating FLOAT NOT NULL
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA RESTAURANTS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('foody.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO restaurants (name, location, cuisine, rating)
VALUES ('Los Mandilones', 'C. de la Lonja de la Seda, 25', 'Mexicana', 9.1),
       ('Pomo dOro', 'Calle Morales 10', 'Italiana', 6.7),
       ('Piratas Rock', 'C. Navales, 33', 'Mediterránea', 9),
       ('La Kujnia', 'C. de Castillejos, 16', 'Contemporánea', 8),
       ('Mamma Maria', 'Calle Palomares 1', 'Italiana', 8.1);
''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 1 - TABLA USERS
# Crear la estructura de la base de datos de la tabla ORDERS.

conn = sqlite3.connect('foody.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD


conn.execute('''
CREATE TABLE users (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name varchar(40) NOT NULL,
    email varchar(40) NOT NULL,
    adress varchar(40) NOT NULL,
    rest_favourite varchar(40) NOT NULL,
    FOREIGN KEY (rest_favourite) REFERENCES orders(name)
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA USERS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('foody.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO users (name, email, adress, rest_favourite)
VALUES ('Petalo', 'petalo@supernena.com', 'Avenida de la Piruleta, 12','Los Mandilones'),
       ('Burbuja', 'burbuja@supernena.com', 'Avenida de la Piruleta, 12', 'Pomo dOro'),
       ('Cactus', 'cactus@supernena.com', 'Avenida de la Piruleta, 12','Piratas Rock'),
       ('Leyre', 'leyrem@outlook.es','C.Prado Merinero 23', 'La Kujnia'),
       ('Ismael','ismaruiz@outlook.es', 'C. Mario Benedetti 33','Mamma Maria'),
       ('Kiara', 'kiara@outlook.es', 'C. Mario Benedetti 33','Los Mandilones');
''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 1 - TABLA ORDERS
# Crear la estructura de la base de datos de la tabla ORDERS.

conn = sqlite3.connect('foody.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD


conn.execute('''
CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INT NOT NULL,
    restaurant_id INT NOT NULL,
    order_time TIMESTAMP,
    delivery_time TIMESTAMP,
    total_amount FLOAT,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id)
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

OperationalError: table orders already exists

In [ ]:
## TAREA 2 - TABLA ORDERS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('foody.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO orders (user_id, restaurant_id, order_time, delivery_time, total_amount)
VALUES (1, 1, '2023-12-12 14:00:00', '2023-12-12 14:45:00', 24.90),
       (4, 1, '2024-01-23 21:20:00', '2024-01-23 21:55:30', 33.80),
       (5, 4, '2024-02-02 13:55:00', '2024-02-02 14:25:30', 17.90),
       (2, 3, '2024-02-12 21:20:00', '2024-02-12 21:47:30', 55.50),
       (3, 5, '2024-02-26 22:10:00', '2024-02-26 22:29:30', 24.75),
       (1, 2, '2024-02-29 14:20:00', '2024-02-29 14:37:30', 29.99),
       (4, 1, '2024-03-01 14:20:00', '2024-03-01 14:48:30', 42.20);
''')

# Guardar los cambios
conn.commit()

In [ ]:
## TAREA 3
#1- ¿Cuántos pedidos se han realizado en cada restaurante durante el último mes?
qry ='''
SELECT restaurants.name, count(total_amount) as TOTAL
FROM orders
JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
WHERE order_time >= '2024-02-03 00:00:00'
group by orders.restaurant_id
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

             name  TOTAL
0  Los Mandilones      1
1       Pomo dOro      1
2    Piratas Rock      1
3     Mamma Maria      1

In [ ]:
## TAREA 3
#2- ¿Cuál es el usuario que ha realizado más pedidos?
qry ='''
SELECT users.name, count(total_amount) as TOTAL
FROM orders
JOIN users
ON orders.user_id = users.user_id
group by orders.user_id
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(1)

               name  TOTAL
0  Petalo Supernena      2

In [ ]:
## TAREA 3
#3- ¿Cuál es el restaurante más popular entre los usuarios?

qry ='''
SELECT name, rating
FROM restaurants
ORDER BY rating DESC
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(1)

             name  rating
0  Los Mandilones     9.1

In [ ]:
## TAREA 3
#4- ¿Cuál es el monto total de ventas realizadas en la plataforma durante el último año?
qry ='''
SELECT sum(total_amount) as Total
FROM orders
WHERE order_time >= '2023-01-01 00:00:00'
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(1)

    Total
0  229.04

## **[Extra] Semana 4 - Revolut, el neobanco**

**Descripción**:

Revolut es una institución financiera que necesita una base de datos para gestionar la información de sus clientes, cuentas bancarias y transacciones. La base de datos les ayudará a mantener un registro preciso de las actividades financieras y a proporcionar un servicio eficiente a sus clientes.

**Datos**:

La base de datos de Revolut contiene tres tablas principales:
- clients (clientes),
- accounts (cuentas) y
- transactions (transacciones).

Aquí está la estructura de cada tabla:

**Tabla clients:**

- client_id (int, clave primaria): Identificador único del cliente.
- name (string): Nombre del cliente.
- email (string): Dirección de correo electrónico del cliente.
- phone (string): Número de teléfono del cliente.
- address (string): Dirección del cliente.

**Tabla accounts:**

- account_id (int, clave primaria): Identificador único de la cuenta bancaria.
- client_id (int): Identificador único del cliente al que pertenece la cuenta.
- account_type (string): Tipo de cuenta bancaria (por ejemplo, corriente, de ahorro).
- balance (decimal): Saldo actual de la cuenta.

**Tabla transactions:**

- transaction_id (int, clave primaria): Identificador único de la transacción.
- account_id (int): Identificador único de la cuenta bancaria asociada a la transacción.
- transaction_type (string): Tipo de transacción (por ejemplo, depósito, retiro, transferencia).
- amount (decimal): Monto de la transacción.
- transaction_date (timestamp): Fecha y hora en la que se realizó la transacción.

**Tareas:**

1. Diseñar e implementar la estructura de la base de datos con las tablas clients, accounts y transactions.
2. Insertar datos de ejemplo en cada tabla para simular clientes, cuentas bancarias y transacciones.
3. Realizar consultas SQL para responder las siguientes preguntas:
- ¿Cuántos clientes tiene el banco?
- ¿Cuál es el saldo promedio de las cuentas de ahorro?
- ¿Cuál es el cliente con el mayor saldo en sus cuentas?
- ¿Cuántas transacciones se realizaron el último mes?

**Entrega:**

Proporciona el script SQL que incluya la creación de las tablas, la inserción de datos y las consultas realizadas para cumplir con las tareas mencionadas.

In [ ]:
## TAREA 1 - TABLA CLIENTS
# Crear la estructura de la base de datos de la tabla ORDERS.

import numpy as np
import pandas as pd #Pandas: para manipulación y análisis de datos
import sqlite3 #para trabajar con BBDD SQLite

conn = sqlite3.connect('revolut.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD


conn.execute('''
CREATE TABLE clients (
    client_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name varchar(40) NOT NULL,
    email varchar(40) NOT NULL,
    phone varchar(40) NOT NULL,
    address varchar(40) NOT NULL
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA CLIENTS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('revolut.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO clients (name, email, phone, address)
VALUES ('Leyre M', 'leyrem@outlook.es','612345678','C. de la Lonja de la Seda, 25'),
       ('Ismael R', 'ismar@outlook.es', '623456789','C. Morales 10'),
       ('Kiara R', 'kiara@guau.es', '634567890', 'C. Navales, 33'),
       ('Diana A', 'diarai@ru.es', '645678901', 'C. de Castillejos, 16'),
       ('Almu M', 'almum@outlook.es', '656789012', 'Calle Palomares 1');
''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
# Para VACIAR TABLA en caso de ERROR:
conn.execute('''
DROP TABLE accounts;
''')
conn.commit()

In [ ]:
## TAREA 1 - TABLA ACCOUNTS
# Crear la estructura de la base de datos de la tabla ORDERS.

conn = sqlite3.connect('revolut.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD


conn.execute('''
CREATE TABLE accounts (
    account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id INTEGER,
    account_type varchar(40) NOT NULL,
    balance FLOAT,
    FOREIGN KEY (client_id) REFERENCES clients(client_id)
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA ACCOUNTS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('revolut.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO accounts (client_id, account_type, balance)
VALUES (1, 'Corriente', 256.80),
       (1, 'Ahorro', 10250.00),
       (2, 'Ahorro', 9750.00),
       (4, 'Corriente', 1247.90),
       (4, 'Ahorro', 255.00),
       (5, 'Ahorro', 2450.00);
''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 1 - TABLA TRANSACTIONS
# Crear la estructura de la base de datos de la tabla ORDERS.

conn = sqlite3.connect('revolut.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD


conn.execute('''
CREATE TABLE transactions (
    transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id INT NOT NULL,
    transaction_type varchar(40) NOT NULL,
    amount FLOAT,
    transaction_date TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);''')

# Guardar los cambios
conn.commit()
# Cerrar la conexión
conn.close()

In [ ]:
## TAREA 2 - TABLA TRANSACTIONS
#Inserta varios registros en cada tabla .

conn = sqlite3.connect('revolut.sqlite') #Establece una conexión a la BBDD SQLite
cur = conn.cursor() #El cursor para ejecutar comandos SQL en la BBDD

conn.execute('''
INSERT INTO transactions (account_id, transaction_type, amount, transaction_date)
VALUES (1, 'Retiro', 50, '2023-12-12 14:37:00'),
       (3, 'Depósito', 250, '2024-01-07 21:15:00'),
       (4, 'Transferencia', 500, '2024-01-12 15:02:00'),
       (5, 'Depósito', 250, '2024-02-29 11:45:00'),
       (6, 'Retiro', 50, '2024-03-03 19:28:00');
''')

# Guardar los cambios
conn.commit()

In [ ]:
#1- ¿Cuántos clientes tiene el banco?

qry ='''
SELECT count(client_id) as total_clientes
FROM clients
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

   total_clientes
0               5

In [ ]:
## TAREA 3
#2- ¿Cuál es el saldo promedio de las cuentas de ahorro?
qry ='''
SELECT avg(balance) as saldo_promedio
FROM accounts
WHERE account_type = 'Ahorro'
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

   saldo_promedio
0         5676.25

In [ ]:
## TAREA 3
#3- ¿Cuál es el cliente con el mayor saldo en sus cuentas?
qry ='''
SELECT clients.name, accounts.balance
FROM accounts
JOIN clients
ON clients.client_id = accounts.client_id
ORDER BY balance DESC
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head(1)

      name  balance
0  Leyre M  10250.0

In [ ]:
## TAREA 3
#4- ¿Cuántas transacciones se realizaron el último mes?
qry ='''
SELECT count(transaction_id) as Total
FROM transactions
WHERE transaction_date >= '2024-02-01 00:00:00'
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

   Total
0      2

In [ ]:
## ADICIONAL
## Si quisiéramos saber cuántas cuentas tiene cada cliente

qry ='''
SELECT client_id as Cliente, count(account_type) as Cuentas
FROM accounts
WHERE client_id
GROUP BY client_id
;'''

#Leemos datos de la BBDD utilizando una consulta SQL y carga en un DataFrame de Pandas
df =pd.read_sql_query(qry, conn)
df.head()

   Cliente  Cuentas
0        1        2
1        2        1
2        4        2
3        5        1

https://datalemur.com/?referralCode=ydDnKOiH